quarkus.datasource.db-kind=mariadb
quarkus.datasource.username=root
quarkus.datasource.password=SUA_SENHA
quarkus.datasource.jdbc.url=jdbc:mariadb://localhost:3306/carioquinha_rio

quarkus.hibernate-orm.database.generation=validate
quarkus.hibernate-orm.log.sql=true